/// The Dart construction against the JavaScript one.
///
/// Every value below was generated by `tool/vectors.mjs`, which computes them
/// with the same arithmetic `web/src/nk-crypto.mjs` uses. This file is the only
/// reason the port may be trusted: without it, a wrong salt or a swapped
/// argument would produce grants that look fine and open nowhere.
import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:nextkey_app/src/nk/crypto.dart';

// ─── Reference vectors — do not edit by hand ────────────────────────────────
const _recipientSecret = 'AwoRGB8mLTQ7QklQV15lbHN6gYiPlp2kq7K5wMfO1dw=';
const _recipientPublic = 'u1D/noKldM+/gg6X9g+5wUPsdBXPUU+M/Zjv9Z4FlhQ=';
const _ephemeralSecret = 'BRAbJjE8R1JdaHN+iZSfqrXAy9bh7PcCDRgjLjlET1o=';
const _ephemeralPublic = 'FO4OB/NOOhcDDG7s9m03BegNHhU/egyls0XoPOnWJkM=';
const _sharedSecret = 'Mt+ndsFrN3RlZa/3AxtQTEII2aDksjB2oIhySar3tQ4=';
const _wrapKey = 'eQ7QWMkNWufPGe+st9xG5h4rT22RJ+wbPNfjc25q8K4=';
const _grantRecordKey = 'nextkey.g2.9d8c6e7d045dc3e37868d9c7160dba44';
const _ackRecordKey = 'nextkey.a2.3dea4f81abccbaf6a01dd4920ff46cbc';
const _signature =
    '0x010e1b2835424f5c697683909daab7c4d1deebf805121f2c394653606d7a8794a1aebbc8d5e2effc091623303d4a5764717e8b98a5b2bfccd9e6f3000d1a273441';
const _identitySecret = 'oj/MJu1WoT6qiFT4DvtjiJSlW7iTaR3RMKPhx4lbIcY=';
const _identityPublic = 'ZWJlwgsPMdY3/npyadgOgYyE30kKgixDmg08YYOAFjo=';
const _identityId = 'NK-82FZB-0D3X7-JV29C';
const _ephForName = '8MfLGsl7abjzsaQ/QEWKKc4hMiaCMLWC7u4WUgbGZ58=';
const _gcmIv = 'AhMkNUZXaHmKm6y9';
const _gcmPlaintext = 'correct horse battery staple';
const _gcmCiphertext = 'LNMMd9fzWxhk/QWGvpP0jCKIi3O/Rk/BF14HMze9TepyKd9h/cK3VV992/4=';

void main() {
  test('a secret gives the same public key as the browser', () async {
    expect(b64(await publicKeyOf(un64(_recipientSecret))), _recipientPublic);
    expect(b64(await publicKeyOf(un64(_ephemeralSecret))), _ephemeralPublic);
  });

  test('both sides reach the same ECDH output', () async {
    final sender =
        await sharedSecret(un64(_ephemeralSecret), un64(_recipientPublic));
    final recipient =
        await sharedSecret(un64(_recipientSecret), un64(_ephemeralPublic));
    expect(b64(sender), _sharedSecret);
    expect(b64(recipient), _sharedSecret);
  });

  test('the wrapping key and the record names match the browser', () async {
    final shared = un64(_sharedSecret);
    final eph = un64(_ephemeralPublic);
    final recip = un64(_recipientPublic);
    expect(b64(await wrapKeyV2(shared, eph, recip)), _wrapKey);
    expect(await grantRecordKey(shared, eph, recip), _grantRecordKey);
    expect(await ackRecordKey(shared, eph, recip), _ackRecordKey);
  });

  test('locateGrant finds the same address from the recipient side', () async {
    final where = await locateGrant(
      ephPublic: un64(_ephemeralPublic),
      mySecret: un64(_recipientSecret),
      myPublic: un64(_recipientPublic),
    );
    expect(where.recordKey, _grantRecordKey);
    expect(b64(where.kek), _wrapKey);
    expect(where.ackKey, _ackRecordKey);
  });

  test('a signature derives the identity key it derives in the browser',
      () async {
    final sk = await identitySecretFromSignature(_signature);
    expect(b64(sk), _identitySecret);
    expect(b64(await publicKeyOf(sk)), _identityPublic);
    expect(await nextkeyId(un64(_identityPublic)), _identityId);
  });

  test('a signature derives the ephemeral key for a name', () async {
    expect(b64(await ephSecretFromSignature(_signature, 'anna.nextkey.eth')),
        _ephForName);
  });

  test('AES-256-GCM opens a ciphertext WebCrypto produced', () async {
    final opened = await unseal(
      {'iv': _gcmIv, 'ct': _gcmCiphertext},
      un64(_wrapKey),
    );
    expect(opened, _gcmPlaintext);
  });

  test('sealing and opening round-trips', () async {
    final key = un64(_wrapKey);
    final record = await seal(key, 'a passphrase with ümläute and 漢字');
    expect(await unseal(record, key), 'a passphrase with ümläute and 漢字');
  });

  test('a tampered ciphertext is refused, not silently wrong', () async {
    final key = un64(_wrapKey);
    final record = await seal(key, 'hello');
    final bytes = un64(record['ct']!);
    bytes[0] ^= 0x01;
    expect(
      () => unseal({'iv': record['iv']!, 'ct': b64(bytes)}, key),
      throwsA(isA<Exception>()),
    );
  });

  test('the NextKey ID matches the browser, and checks itself', () async {
    expect(await nextkeyId(un64(_recipientPublic)), 'NK-QYJB5-H28ZF-EC0ZB');
    expect(await nextkeyId(un64(_ephemeralPublic)), 'NK-JTVWV-JZ821-6E3MR');
    expect(looksLikeNextkeyId('NK-QYJB5-H28ZF-EC0ZB'), isTrue);
    expect(looksLikeNextkeyId('nk-qyjb5-h28zf-ec0zb'), isTrue);
    // A transposition the check symbol is there to catch.
    expect(looksLikeNextkeyId('NK-QYJ5B-H28ZF-EC0ZB'), isFalse);
    expect(looksLikeNextkeyId('NK-IIIII-IIIII-IIIII'), isFalse);
    expect(looksLikeNextkeyId('not an id'), isFalse);
  });

  test('padding hides the length of a short secret', () {
    expect(utf8.encode(padSecret('hello')).length, 256);
    expect(utf8.encode(padSecret('x' * 300)).length, 512);
    expect(unpadSecret(padSecret('hello')), 'hello');
    // A record written before padding existed comes back unchanged.
    expect(unpadSecret('hello'), 'hello');
  });

  test('the name rule refuses what the resolver would mean differently', () {
    expect(ensName.hasMatch('anna.nextkey.eth'), isTrue);
    expect(ensName.hasMatch('Anna.nextkey.eth'), isFalse);
    expect(ensName.hasMatch('eth'), isFalse);
  });
}
