// Reference vectors for the Dart port of web/src/nk-crypto.mjs.
// Pure node:crypto — same arithmetic as @noble (X25519, HKDF-SHA256, AES-256-GCM).
import crypto from 'node:crypto'

const b64 = (u8) => Buffer.from(u8).toString('base64')
const un64 = (s) => new Uint8Array(Buffer.from(s, 'base64'))
const hex = (u8) => Buffer.from(u8).toString('hex')
const utf8 = (s) => new Uint8Array(Buffer.from(s, 'utf8'))

const privFromRaw = (raw) => crypto.createPrivateKey({
  key: { kty: 'OKP', crv: 'X25519', d: Buffer.from(raw).toString('base64url'), x: '' },
  format: 'jwk',
})
const pubFromRaw = (raw) => crypto.createPublicKey({
  key: { kty: 'OKP', crv: 'X25519', x: Buffer.from(raw).toString('base64url') },
  format: 'jwk',
})
const rawPubOf = (sk) => new Uint8Array(Buffer.from(
  crypto.createPublicKey(privFromRaw(sk)).export({ format: 'jwk' }).x, 'base64url'))
const shared = (sk, pk) => new Uint8Array(
  crypto.diffieHellman({ privateKey: privFromRaw(sk), publicKey: pubFromRaw(pk) }))
const hkdf = (ikm, salt, info, len) =>
  new Uint8Array(crypto.hkdfSync('sha256', ikm, salt, info, len))
const sha256 = (u8) => new Uint8Array(crypto.createHash('sha256').update(u8).digest())

// ─── the NextKey ID ────────────────────────────────────────────────────────
const B32 = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'
const checkSymbol = (symbols) => B32[symbols.reduce((a, v, i) => a + v * (i + 1), 0) % 32]
const nextkeyId = (pub) => {
  const h = sha256(pub)
  let bits = 0n
  for (let i = 0; i < 9; i++) bits = (bits << 8n) | BigInt(h[i])
  bits >>= 2n
  const symbols = []
  for (let i = 13; i >= 0; i--) symbols[i] = Number((bits >> BigInt(5 * (13 - i))) & 31n)
  const s = symbols.map((v) => B32[v]).join('') + checkSymbol(symbols)
  return `NK-${s.slice(0, 5)}-${s.slice(5, 10)}-${s.slice(10, 15)}`
}

const pairing = (a, b) => new Uint8Array([...a, ...b])

// Deterministic test material: not keys anybody uses.
const recipSk = new Uint8Array(32).fill(0).map((_, i) => (i * 7 + 3) & 0xff)
const ephSk = new Uint8Array(32).fill(0).map((_, i) => (i * 11 + 5) & 0xff)
const recipPk = rawPubOf(recipSk)
const ephPk = rawPubOf(ephSk)
const sh = shared(ephSk, recipPk)
const shR = shared(recipSk, ephPk)
if (hex(sh) !== hex(shR)) throw new Error('ECDH disagrees with itself')

const wrap = hkdf(sh, pairing(ephPk, recipPk), utf8('nextkey/v2/wrap'), 32)
const tag = hex(hkdf(sh, pairing(ephPk, recipPk), utf8('nextkey/v2/tag'), 16))
const ack = hex(hkdf(sh, pairing(ephPk, recipPk), utf8('nextkey/v2/ack'), 16))
const sealInfo = hkdf(sh, pairing(ephPk, recipPk), utf8('nextkey/v2/eph-seal'), 32)

// A signature-shaped 65-byte value, so the derivation is exercised end to end.
const sig = new Uint8Array(65).fill(0).map((_, i) => (i * 13 + 1) & 0xff)
const identitySk = hkdf(sig, utf8('nextkey/v2/identity'), utf8('identity'), 32)
const ephFromSig = hkdf(sig, utf8('nextkey/v2/eph'), utf8('anna.nextkey.eth'), 32)

// AES-256-GCM with a fixed IV, so the Dart side can check the exact bytes.
const iv = new Uint8Array(12).fill(0).map((_, i) => (i * 17 + 2) & 0xff)
const plaintext = 'correct horse battery staple'
const c = crypto.createCipheriv('aes-256-gcm', wrap, iv)
const ct = Buffer.concat([c.update(plaintext, 'utf8'), c.final(), c.getAuthTag()])

const identityPk = rawPubOf(identitySk)

const out = {
  note: 'Generated by nkvec/vectors.mjs — reference values for lib/src/nk/crypto.dart.',
  recipientSecret: b64(recipSk),
  recipientPublic: b64(recipPk),
  ephemeralSecret: b64(ephSk),
  ephemeralPublic: b64(ephPk),
  sharedSecret: b64(sh),
  wrapKey: b64(wrap),
  grantRecordKey: `nextkey.g2.${tag}`,
  ackRecordKey: `nextkey.a2.${ack}`,
  ephSealKey: b64(sealInfo),
  signature: '0x' + hex(sig),
  identitySecret: b64(identitySk),
  identityPublic: b64(identityPk),
  identityNextkeyId: nextkeyId(identityPk),
  ephSecretForName: { name: 'anna.nextkey.eth', secret: b64(ephFromSig) },
  aesGcm: { key: b64(wrap), iv: b64(iv), plaintext, ciphertext: b64(ct) },
  ids: [
    { pubkey: b64(recipPk), id: nextkeyId(recipPk) },
    { pubkey: b64(ephPk), id: nextkeyId(ephPk) },
    { pubkey: b64(new Uint8Array(32)), id: nextkeyId(new Uint8Array(32)) },
  ],
  padding: { input: 'hello', paddedLength: 256 },
}
console.log(JSON.stringify(out, null, 2))
